### ISSUE TITLE
Bug: Buscar informações do usuário, ao acessar perifl informando o id do usuário

### ISSUE THREAD

**Issue by rodgeraraujo** [rodgeraraujo/SysFoodPW1#5]
Não busca informações referentes ao usuário de determinado id.

**Comment by rodgeraraujo** [comment]
Criar método que busque os dados do usuário pelo ID.

**Comment by rodgeraraujo** [comment]
Método criado; Corrigir problema na busca.

**Comment by lucasgf07** [comment]
Corrigido
